/** Luxembourg communes for B2C location filter */
export const LUXEMBOURG_COMMUNES = [
  "Luxembourg",
  "Esch-sur-Alzette",
  "Differdange",
  "Dudelange",
  "Pétange",
  "Sanem",
  "Hesperange",
  "Bertrange",
  "Mamer",
  "Strassen",
  "Niederanven",
  "Walferdange",
  "Steinsel",
  "Sandweiler",
  "Schuttrange",
  "Kirchberg",
  "Limpertsberg",
  "Belair",
  "Merl",
  "Hollerich",
  "Bonnevoie",
  "Cessange",
  "Gasperich",
  "Clausen",
  "Pfaffenthal",
  "Grund",
  "Ville Haute",
]
